<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
/** @var \YuliiaK\RegularCustomer\ViewModel\Customer\RequestList $viewModel */
$viewModel = $block->getData('view_model');
?>
<ul>
    <?php /** @var \YuliiaK\RegularCustomer\Model\CustomerRequest $customerRequest */ ?>
    <?php foreach ($viewModel->getCustomerRequestCollection() as $customerRequest): ?>
        <?php $product = $viewModel->getProduct((int) $customerRequest->getProductId()); ?>
        <li>
            <span><?= $escaper->escapeHtml(__('Requested product: %1', $product ? $product->getName() : '-')) ?></span>
            <br/>
            <span><?= $escaper->escapeHtml(__('Message: %1', $customerRequest->getMessage())) ?></span>
        </li>
    <?php endforeach; ?>
</ul>
